#! /bin/python

import sys
import os
from pathlib import Path

sys.path.append(str(Path(os.curdir).parent.absolute().parent.absolute()))

from typing import Optional
import typer
from rich import print
from clowder import functions
from clowder.status import Status

app = typer.Typer()


@app.command("untrack")
def untrack(investigation_name: str):
    print(functions.untrack(investigation_name))


@app.command("track")
def track(investigation_name: Optional[str] = None):
    print(functions.track(investigation_name))


@app.command("create-from-template")
def duplicate(from_investigation_name: str, new_investigation_name: str):
    print(functions.create_from_template(from_investigation_name, new_investigation_name))


@app.command("delete")
def delete(investigation_name: str, keep_clearml: bool = False, keep_google_drive: bool = False, keep_s3: bool = False):
    functions.delete(investigation_name, not keep_clearml, not keep_google_drive, not keep_s3)


@app.command("urlfor")
def urlfor(investigation_name: str):
    print(functions.urlfor(investigation_name))


@app.command("idfor")
def idfor(investigation_name: str):
    print(functions.idfor(investigation_name))


@app.command("cancel")
def cancel(investigation_name: str):
    functions.cancel(investigation_name)


@app.command("run")
def run(investigation_name: str, force_rerun: bool = False):
    print(functions.run(investigation_name, force_rerun))


@app.command("status")
def status(investigation_name: Optional[str] = None, sync: bool = True, verbose: bool = False):
    for inv_name, obj in functions.status(investigation_name, sync).items():
        color = _map_status_color(obj["status"])
        if verbose:
            print(f"[bold]{inv_name}[/bold]")
            print(f"\tStatus:[{color}]\t{obj['status'].value}[/{color}]")
            print(f"\tGDrive url:\t{obj['gdrive_url']}")
            print(f"\tExperiments:")
            for exp_name, exp_obj in obj["experiments"].items():
                print(f"\t[bold]{exp_name}[/bold]")
                print(f"\tStatus:\t{exp_obj['status']}")
                print(f"\tClearML url:\t{exp_obj['clearml_task_url']}")
        else:
            print(inv_name, f"[{color}]\t{obj['status'].value}[/{color}]")


@app.command("sync")
def sync(investigation_name: Optional[str] = None):
    functions.sync(investigation_name)
    print(
        f"[green]Successfully synced {investigation_name if investigation_name else 'all investigations in this context'}[/green]"
    )


@app.command("create")
def create(investigation_name: str):
    functions.create(investigation_name)
    print(f"[green]Investigation {investigation_name} successfully created")


@app.command("use-context")
def use_context(root_folder_id: str):
    functions.use_context(root_folder_id)
    print(f"[green]Success! Now using context {root_folder_id}[/green]")


@app.command("list")
def list():
    for inv in functions.list_inv():
        print(inv.name)


@app.command("current-context")
def current_context():
    print(functions.current_context())


@app.command("init")
def init():
    functions.init()


def _map_status_color(status: Status) -> str:
    # Mysterious comparison behavior; comparing by value instead
    if status.value == Status.Created.value:
        return "blue"
    if status.value == Status.Running.value:
        return "yellow"
    if status.value == Status.Completed.value:
        return "green"
    if status.value == Status.Canceled.value:
        return "pink"
    if status.value == Status.Failed.value:
        return "red"
    return "white"


if __name__ == "__main__":
    app()
